/*******************************************************************************
 * This file is part of ISPyB.
 * 
 * ISPyB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * ISPyB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with ISPyB.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors : S. Delageniere, R. Leal, L. Launer, K. Levik, S. Veyrier, P. Brenchereau, M. Bodin, A. De Maria Antolinos
 ******************************************************************************************************************************/

package ispyb.server.biosaxs.services.sql;

public class SQLQueryKeeper {

	public static String getExperimentDescription() {
		return "SELECT Buffer.acronym as buffer, Macromolecule.acronym as macromolecule, Specimen.*, Measurement.*, SamplePlatePosition.*, SamplePlate.*  FROM \r\n"
				+ "Experiment experiment\r\n"
				+ "LEFT JOIN Specimen on Specimen.experimentId = experiment.experimentId\r\n"
				+ "LEFT JOIN Macromolecule on Macromolecule.macromoleculeId = Specimen.macromoleculeId\r\n"
				+ "LEFT JOIN Buffer on Buffer.bufferId = Specimen.bufferId\r\n"
				+ "LEFT JOIN Measurement on Measurement.specimenId = Specimen.specimenId\r\n"
				+ "LEFT JOIN SamplePlatePosition on Specimen.samplePlatePositionId = SamplePlatePosition.samplePlatePositionId\r\n"
				+ "LEFT JOIN SamplePlate on SamplePlate.samplePlateId = SamplePlatePosition.samplePlateId ";
	}


	@Deprecated
	public static String getAnalysisQuery() {
		return "select \r\n"
				+ "    exp.experimentType as experimentType,\r\n"
				+ "    exp.sessionId as sessionId,\r\n"
				+ "    exp.creationDate as experimentCreationDate,\r\n"
				+ "    (select \r\n"
				+ "        timeStart\r\n"
				+ "    from\r\n"
				+ "        Run r\r\n"
				+ "    where\r\n"
				+ "        r.runId = m.runId) as timeStart,\r\n"
				+ "    p.proposalCode,\r\n"
				+ "    p.proposalNumber,\r\n"
				+ "    m.priorityLevelId,\r\n"
				+ "    m.code,\r\n"
				+ "    m.exposureTemperature,\r\n"
				+ "    m.transmission,\r\n"
				+ "    m.comments as measurementComments,\r\n"
				+ "    exp.comments as expermientComments,\r\n"
				+ "    exp.experimentId,\r\n"
				+ "    s.concentration as conc,\r\n"
				+ "    bu.acronym as bufferAcronym,\r\n"
				+ "    ma.acronym as macromoleculeAcronym,\r\n"
				+ "    bu.bufferId as bufferId,\r\n"
				+ "    ma.macromoleculeId as macromoleculeId,\r\n"
				+ "    (select \r\n"
				+ "        su.substractedFilePath\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as subtractedFilePath,\r\n"
				+ "    (select \r\n"
				+ "        su.rgGuinier\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as rgGuinier,\r\n"
				+ "    (select \r\n"
				+ "        su.firstPointUsed\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as firstPointUsed,\r\n"
				+ "    (select \r\n"
				+ "        su.lastPointUsed\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as lastPointUsed,\r\n"
				+ "    (select \r\n"
				+ "        su.I0\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as I0,\r\n"
				+ "    (select \r\n"
				+ "        su.isagregated\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as isagregated,\r\n"
				+ "    (select \r\n"
				+ "        su.subtractionId\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as subtractionId,\r\n"
				+ "    (select \r\n"
				+ "        su.rgGnom\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as rgGnom,\r\n"
				+ "    (select \r\n"
				+ "        su.total\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as total,\r\n"
				+ "    (select \r\n"
				+ "        su.dmax\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as dmax,\r\n"
				+ "    (select \r\n"
				+ "        su.volume\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as volume,\r\n"
				+ "    (select \r\n"
				+ "        su.i0stdev\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as i0stdev,\r\n"
				+ "    (select \r\n"
				+ "        su.quality\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as quality,\r\n"
				+ "    (select \r\n"
				+ "        su.creationTime\r\n"
				+ "    from\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.subtractionId = (select \r\n"
				+ "            max(su2.subtractionId)\r\n"
				+ "        from\r\n"
				+ "            Subtraction su2\r\n"
				+ "        where\r\n"
				+ "            su2.dataCollectionId = dc.dataCollectionId)) as substractionCreationTime,\r\n"
				+ "    (select \r\n"
				+ "        mtd2.measurementId\r\n"
				+ "    from\r\n"
				+ "        MeasurementToDataCollection mtd2\r\n"
				+ "    where\r\n"
				+ "        mtd.dataCollectionId = mtd2.dataCollectionId and mtd2.dataCollectionOrder = 1) as bufferBeforeMeasurementId,\r\n"
				+ "    (select \r\n"
				+ "        mtd2.measurementId\r\n"
				+ "    from\r\n"
				+ "        MeasurementToDataCollection mtd2\r\n"
				+ "    where\r\n"
				+ "        mtd.dataCollectionId = mtd2.dataCollectionId and mtd2.dataCollectionOrder = 3) as bufferAfterMeasurementId,\r\n"
				+ "    (select \r\n"
				+ "        framesMerge\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = bufferBeforeMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = bufferBeforeMeasurementId)) as bufferBeforeFramesMerged,\r\n"
				+ "    (select \r\n"
				+ "        framesCount\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = bufferBeforeMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = bufferBeforeMeasurementId)) as bufferBeforeFramesCount,\r\n"
				+ "    (select \r\n"
				+ "        mergeId\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = bufferBeforeMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = bufferBeforeMeasurementId)) as bufferBeforeMergeId,\r\n"
				+ "    (select \r\n"
				+ "        averageFilePath\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = bufferBeforeMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = bufferBeforeMeasurementId)) as bufferBeforeAverageFilePath,\r\n"
				+ "    (select \r\n"
				+ "        mtd2.measurementId\r\n"
				+ "    from\r\n"
				+ "        MeasurementToDataCollection mtd2\r\n"
				+ "    where\r\n"
				+ "        mtd.dataCollectionId = mtd2.dataCollectionId and mtd2.dataCollectionOrder = 2) as sampleMeasurementId,\r\n"
				+ "    (select \r\n"
				+ "        mergeId\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = sampleMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = sampleMeasurementId)) as sampleMergeId,\r\n"
				+ "    (select \r\n"
				+ "        averageFilePath\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = sampleMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = sampleMeasurementId)) as averageFilePath,\r\n"
				+ "    (select \r\n"
				+ "        framesMerge\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = sampleMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = sampleMeasurementId)) as framesMerge,\r\n"
				+ "    (select \r\n"
				+ "        m2.framesCount\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = sampleMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = sampleMeasurementId)) as framesCount,\r\n"
				+ "    (select \r\n"
				+ "        framesMerge\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = bufferAfterMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = bufferAfterMeasurementId)) as bufferAfterFramesMerged,\r\n"
				+ "    (select \r\n"
				+ "        framesCount\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = bufferAfterMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = bufferAfterMeasurementId)) as bufferAfterFramesCount,\r\n"
				+ "    (select \r\n"
				+ "        mergeId\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = bufferAfterMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = bufferAfterMeasurementId)) as bufferAfterMergeId,\r\n"
				+ "    (select \r\n"
				+ "        m2.averageFilePath\r\n"
				+ "    from\r\n"
				+ "        Merge m2\r\n"
				+ "    where\r\n"
				+ "        m2.measurementId = bufferAfterMeasurementId and m2.mergeId in (select \r\n"
				+ "            max(m3.mergeId)\r\n"
				+ "        from\r\n"
				+ "            Merge m3\r\n"
				+ "        where\r\n"
				+ "            m3.measurementId = bufferAfterMeasurementId)) as bufferAfterAverageFilePath,\r\n"
				+ "    (select \r\n"
				+ "        modelList.modelListId\r\n"
				+ "    from\r\n"
				+ "        ModelList modelList,\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and modelList.modelListId = ab.modelListId and ab.abInitioModelId = subToAb.abInitioId and subToAb.subtractionId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as modelListId,\r\n"
				+ "    (select \r\n"
				+ "        nsdFilePath\r\n"
				+ "    from\r\n"
				+ "        ModelList modelList,\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and modelList.modelListId = ab.modelListId and ab.abInitioModelId = subToAb.abInitioId and subToAb.subtractionId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as nsdFilePath,\r\n"
				// commented because the query is duplicated
				// + "    (select \r\n"
				// + "        modelList.modelListId\r\n"
				// + "    from\r\n"
				// + "        ModelList modelList,\r\n"
				// + "        AbInitioModel ab,\r\n"
				// + "        SubtractionToAbInitioModel subToAb,\r\n"
				// + "        Subtraction su\r\n"
				// + "    where\r\n"
				// +
				// "        su.dataCollectionId = dc.dataCollectionId and modelList.modelListId = ab.modelListId and ab.abInitioModelId = subToAb.abInitioId and subToAb.subtractionId and subToAb.abInitioId = (select \r\n"
				// + "            max(subToAb2.abInitioId)\r\n"
				// + "        from\r\n"
				// + "            SubtractionToAbInitioModel subToAb2\r\n"
				// + "        where\r\n"
				// +
				// "            subToAb2.subtractionId = su.subtractionId)) as modelListId,\r\n"
				+ "    (select \r\n"
				+ "        chi2RgFilePath\r\n"
				+ "    from\r\n"
				+ "        ModelList modelList,\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and modelList.modelListId = ab.modelListId and ab.abInitioModelId = subToAb.abInitioId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as chi2RgFilePath,\r\n"
				+ "    (select \r\n"
				+ "        pdbFile\r\n"
				+ "    from\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Model model,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and model.modelId = ab.averagedModelId and ab.abInitioModelId = subToAb.abInitioId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as averagedModel,\r\n"
				+ "    (select \r\n"
				+ "        modelId\r\n"
				+ "    from\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Model model,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and model.modelId = ab.averagedModelId and ab.abInitioModelId = subToAb.abInitioId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as averagedModelId,\r\n"
				+ "    (select \r\n"
				+ "        pdbFile\r\n"
				+ "    from\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Model model,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and model.modelId = ab.rapidShapeDeterminationModelId and ab.abInitioModelId = subToAb.abInitioId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as rapidShapeDeterminationModel,\r\n"
				+ "    (select \r\n"
				+ "        modelId\r\n"
				+ "    from\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Model model,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and model.modelId = ab.rapidShapeDeterminationModelId and ab.abInitioModelId = subToAb.abInitioId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as rapidShapeDeterminationModelId,\r\n"
				+ "    (select \r\n"
				+ "        pdbFile\r\n"
				+ "    from\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Model model,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and model.modelId = ab.shapeDeterminationModelId and ab.abInitioModelId = subToAb.abInitioId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as shapeDeterminationModel,\r\n"
				+ "    (select \r\n"
				+ "        modelId\r\n"
				+ "    from\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Model model,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and model.modelId = ab.shapeDeterminationModelId and ab.abInitioModelId = subToAb.abInitioId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as shapeDeterminationModelId,\r\n"
				+ "    (select \r\n"
				+ "        ab.abInitioModelId\r\n"
				+ "    from\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and ab.abInitioModelId = subToAb.abInitioId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as abInitioModelId,\r\n"
				+ "    (select \r\n"
				+ "        comments\r\n"
				+ "    from\r\n"
				+ "        AbInitioModel ab,\r\n"
				+ "        SubtractionToAbInitioModel subToAb,\r\n"
				+ "        Subtraction su\r\n"
				+ "    where\r\n"
				+ "        su.dataCollectionId = dc.dataCollectionId and ab.abInitioModelId = subToAb.abInitioId and subToAb.abInitioId = (select \r\n"
				+ "            max(subToAb2.abInitioId)\r\n"
				+ "        from\r\n"
				+ "            SubtractionToAbInitioModel subToAb2\r\n"
				+ "        where\r\n"
				+ "            subToAb2.subtractionId = su.subtractionId)) as comments\r\n"
				+ "from\r\n"
				+ "    Experiment exp,\r\n"
				+ "    Buffer bu,\r\n"
				+ "    SaxsDataCollection dc,\r\n"
				+ "    Macromolecule ma,\r\n"
				+ "    MeasurementToDataCollection mtd,\r\n"
				+ "    Specimen s,\r\n"
				+ "    Measurement m,\r\n"
				+ "    Proposal p\r\n"
				+ "where\r\n"
				+ "    bu.bufferId = s.bufferId and p.proposalId = exp.proposalId and m.specimenId = s.specimenId "
				+ " and dc.dataCollectionId = mtd.dataCollectionId and mtd.measurementId = m.measurementId and s.macromoleculeId = ma.macromoleculeId and s.experimentId = exp.experimentId "
				+ " and exp.experimentType != 'TEMPLATE' ";

	}
}
